language: python
python:
    - "2.7"
    - "3.6"
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
# command to install dependencies
install:
    - pip install .
    - pip install tox
# command to run tests
script: tox
