language: python
cache: pip
python:
    - "3.6"
# command to install dependencies
#install:
#    - pip install --upgrade -r requirements.txt
#    - pip install --upgrade .
#    - pip install --upgrade tox-travis
# command to run tests
script: tox
after_success: coveralls
