language: python
cache: pip
python:
    - "2.7"
    - "3.6"
# command to install dependencies
install:
    - pip install --upgrade .
    - pip install --upgrade tox-travis
# command to run tests
script: tox-travis
